FROM ubuntu:24.04

RUN apt-get update && apt-get -y install \
curl \
grep \
inetutils-ping \
libpq-dev \
iproute2 \
nmap \
openssh-client openssh-server \
procps python3-distutils python3-pip python3-apt \
sudo \
tree \
unzip \
zip